PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX bab: <https://w3id.org/babelon/>
DELETE {?axiom ?p ?o .}
WHERE {
  ?axiom a owl:Axiom ;
         owl:annotatedProperty rdfs:label ;
         bab:translation_status "CANDIDATE" .
 ?axiom ?p ?o .
}